#- name: "5 Access, Authentication and Authorization"
#  include_tasks: section_5.1.yml

- name: "5.2 Configure SSH Server"
  include_tasks: section_5.2.yml

- name: "5.3 Configure privilege escalation"
  include_tasks: section_5.3.yml

- name: "5.4 Configure PAM"
  include_tasks: section_5.4.yml

- name: "5.5 User Accounts and Environment"
  include_tasks: section_5.5.yml

