- name: "4.2.1 Configure journald"
  include_tasks: section_4.2.1.yml
  # in Oracle: 4.2.2

- name: "4.2.2 Configure rsyslog"
  include_tasks: section_4.2.2.yml
  # in Oracle: 4.2.1

- name: "4.2.3 Ensure all logfiles have appropriate permissions and ownership (Automated)"   # only temporary solution!
  become: yes
  block:
    - name: "4.2.3 Ensure all logfiles have appropriate permissions and ownership (Automated) |-> create script"
      copy:
        src: etc/cron.daily/var_log_perm.sh
        dest: /etc/cron.daily/var_log_perm.sh
        owner: root
        group: root
        mode: 0750
    - name: "4.2.3 Ensure all logfiles have appropriate permissions and ownership (Automated) |-> run script"
      command: "/bin/bash /etc/cron.daily/var_log_perm.sh"
      ignore_errors: True
  when: level1|bool
  tags:
  - section4
  - section4.2
  - section4.2.3