- name: "4.1.1 Ensure auditing is enabled"
  include_tasks: section_4.1.1.yml
  when: level2|bool

- name: "4.1.2 Configure Data Retention"
  include_tasks: section_4.1.2.yml
  when: level2|bool

- name: "4.1.3 Configure auditd rules"
  include_tasks: section_4.1.3.yml
  when: level2|bool

- name: "4.1.4 Configure auditd file access"
  include_tasks: section_4.1.4.yml


