- name: "3.3.1 Ensure source routed packets are not accepted (Automated)"
  become: yes
  sysctl:
    name: "{{ item }}"
    value: '0'
    state: present
    reload: true
    sysctl_set: true
    ignoreerrors: true
  with_items:
    - net.ipv4.conf.all.accept_source_route
    - net.ipv4.conf.default.accept_source_route
    - net.ipv6.conf.all.accept_source_route
    - net.ipv6.conf.default.accept_source_route
  when: level1|bool
  tags:
    - section3
    - section3.3
    - section3.3.1

- name: "3.3.2 Ensure ICMP redirects are not accepted (Automated)"
  become: yes
  sysctl:
    name: "{{ item }}"
    value: '0'
    state: present
    reload: true
    sysctl_set: true
    ignoreerrors: true
  with_items:
    - net.ipv4.conf.all.accept_redirects
    - net.ipv4.conf.default.accept_redirects
    - net.ipv6.conf.all.accept_redirects
    - net.ipv6.conf.default.accept_redirects
  when: level1|bool
  tags:
    - section3
    - section3.3
    - section3.3.2

- name: "3.3.3 Ensure secure ICMP redirects are not accepted (Automated)"
  become: yes
  sysctl:
    name: "{{ item }}"
    value: '0'
    state: present
    reload: true
    sysctl_set: true
    ignoreerrors: true
  with_items:
    - net.ipv4.conf.default.secure_redirects 
    - net.ipv4.conf.all.secure_redirects
  when: level1|bool
  tags:
    - section3
    - section3.3
    - section3.3.3

- name: "3.3.4 Ensure suspicious packets are logged (Automated)"
  become: yes
  sysctl:
    name: "{{ item }}"
    value: '1'
    state: present
    reload: true
    sysctl_set: true
    ignoreerrors: true
  with_items:
    - net.ipv4.conf.all.log_martians
    - net.ipv4.conf.default.log_martians
  when: level1|bool
  tags:
    - section3
    - section3.3
    - section3.3.4

- name: "3.3.5 Ensure broadcast ICMP requests are ignored (Automated)"
  become: yes
  sysctl:
    name: "net.ipv4.icmp_echo_ignore_broadcasts"
    value: '1'
    state: present
    reload: true
    sysctl_set: true
    ignoreerrors: true
  when: level1|bool
  tags:
    - section3
    - section3.3
    - section3.3.5

- name: "3.3.6 Ensure bogus ICMP responses are ignored (Automated)"
  become: yes
  sysctl:
    name: " icmp_ignore_bogus_error_responses"
    value: '1'
    state: present
    reload: true
    sysctl_set: true
    ignoreerrors: true
  when: level1|bool
  tags:
    - section3
    - section3.3
    - section3.3.6

- name: "3.3.7 Ensure Reverse Path Filtering is enabled (Automated)"
  become: yes
  sysctl:
    name: "{{ item }}"
    value: '1'
    state: present
    reload: true
    sysctl_set: true
    ignoreerrors: true
  with_items:
    - net.ipv4.conf.all.rp_filter 
    - net.ipv4.conf.default.rp_filter
  when: level1|bool
  tags:
    - section3
    - section3.3
    - section3.3.7

- name: "3.3.8 Ensure TCP SYN Cookies is enabled (Automated)"
  become: yes
  sysctl:
    name: "net.ipv4.tcp_syncookies"
    value: '1'
    state: present
    reload: true
    sysctl_set: true
    ignoreerrors: true
  when: level1|bool
  tags:
    - section3
    - section3.3
    - section3.3.8

- name: "3.3.9 Ensure IPv6 router advertisements are not accepted (Automated)"
  become: yes
  sysctl:
    name: "{{ item }}"
    value: '0'
    state: present
    reload: true
    sysctl_set: true
    ignoreerrors: true
  with_items:
    - net.ipv6.conf.all.accept_ra
    - net.ipv6.conf.default.accept_ra
  when: level1|bool
  tags:
    - section3
    - section3.3
    - section3.3.9

