
- name: "read mounts"
  set_fact:
    mounts: "{{ ansible_mounts | map(attribute='mount') | list }}"

- name: Check if autofs exists
  shell: "if systemctl | grep -q autofs; then echo true; else echo false; fi;"
  register: service_autofs_exists

- name: Set facts for Oracle
  set_fact:
    logical_volume_group: ol
  when: ansible_os_family == "RedHat"
    

- name: Set facts for Debian
  set_fact:
    logical_volume_group: deb
  when: ansible_os_family == "Debian"

  #- name: "get package_facts"
  #package_facts:
  #  manager: "apt"


