- name: |
    "1.7.1 Ensure message of the day is configured properly (Automated)"
    "1.7.4 Ensure permissions on /etc/motd are configured (Automated)"
  become: yes
  copy:
    dest: /etc/motd
    content: "" 
    owner: root
    group: root
    mode: 0644
  when: level1|bool
  tags:
    - section1
    - section1.7
    - section1.7.1
    - section1.7.4

- name: |
    "1.7.2 Ensure local login warning banner is configured properly (Automated)"
    "1.7.3 Ensure remote login warning banner is configured properly (Automated"
    "1.7.5 Ensure permissions on /etc/issue are configured (Automated)"
    "1.7.6 Ensure permissions on /etc/issue.net are configured (Automated)"
  become: yes
  copy:
    dest: "{{ item }}"
    content: "{{ content_login_banner }}"
    owner: root
    group: root
    mode: 0644
  with_items:
      - /etc/issue
      - /etc/issue.net
  when: level1|bool
  tags:
    - section1
    - section1.7
    - section1.7.2
    - section1.7.3
    - section1.7.5
    - section1.7.6

