- name: |
    "2.3.1 Ensure NIS Client is not installed (Automated)"
    "2.3.2 Ensure rsh client is not installed (Automated)"
    "2.3.3 Ensure talk client is not installed (Automated)"
    "2.3.4 Ensure telnet client is not installed (Automated)"
    "2.3.5 Ensure LDAP client is not installed (Automated)"
    "2.3.6 Ensure TFTP client is not installed (Automated)"
  become: yes
  dnf: 
    name: ["ypbind", "rsh", "talk", "telnet", "openldap-clients", "tftp"]
    state: absent
    autoremove: yes
  when: level1|bool
  tags:
    - section2
    - section2.3
    - section2.3.1
    - section2.3.2
    - section2.3.3
    - section2.3.4
    - section2.3.5
    - section2.3.6

