- name: "1.1.3.1 Ensure /var is a separate partition (Automated)"
  become: yes
  assert:
    that: "'/var' in mounts"
    fail_msg: "Failed! Mountpoint /var is mandatory and must be created during intitial setup"
    success_msg: "Success!"
  when:
    - level2|bool == True

- name: |
    1.1.3.2 | Ensure nodev option set on /var partition
    1.1.3.3 | Ensure nosuid option set on /var partition
  become: yes
  mount:
      name: /var
      src: "{{ item.device }}"
      fstype: "{{ item.fstype }}"
      state: present
      opts: defaults,nodev,nosuid
  notify: 
    - remount var
  loop: "{{ ansible_mounts }}"
  loop_control:
    label: "{{ item.mount }}"
  when:
    - item.mount == '/var'
    - level1|bool == True

