
- name: "1.1.9 Disable Automounting (Automated)"
  become: yes
  systemd:
    name: autofs
    state: stopped
    enabled: no
    masked: yes
  when:
#    - service_autofs_exists|bool 
    - level1|bool == True
  tags:
    - section1
    - section1.1
    - section1.1.9
